version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow/mlruns  # Save experiments locally
      - ./artifacts:/mlflow/artifacts  # Save model artifacts locally
    command: >
      mlflow server 
      --backend-store-uri /mlflow/mlruns 
      --default-artifact-root /mlflow/artifacts 
      --host 0.0.0.0
